name:         sendxmpp
version:      1.23
version_from: sendxmpp
installdirs:  site
requires:
    Getopt::Long:                  2
    Net::XMPP:                     1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
